# frontend/nginx.conf
server {
  listen 80;
  server_name localhost;

  # Define a raiz onde estão os arquivos do Angular
  root /usr/share/nginx/html;
  index index.html index.htm;

  # Configuração crucial para SPAs:
  # Se o Nginx não encontrar um arquivo correspondente à URL (ex: /pagina-cliente),
  # ele serve o index.html, e o roteador do Angular assume o controle.
  location / {
    try_files $uri $uri/ /index.html;
  }
}